# Generated by Django 6.0.4 on 2026-04-09 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('permit_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('county_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subcounty_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ward_name', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspector_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inspection_date', models.DateTimeField()),
                ('next_inspection_date', models.DateTimeField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('personnel', models.JSONField(blank=True, default=list)),
                ('areas_affected', models.JSONField(blank=True, default=list)),
                ('pest_types', models.JSONField(blank=True, default=list)),
                ('chemicals_used', models.JSONField(blank=True, default=list)),
                ('chemical_dosages', models.JSONField(blank=True, default=list)),
                ('treatment_methods', models.JSONField(blank=True, default=list)),
                ('issues_found', models.JSONField(blank=True, default=list)),
                ('pest_sightings', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('housekeeping_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('waste_management_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('stacking_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('overall_sanitation_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('photo_meta', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('is_draft', models.BooleanField(default=False)),
                ('approval_status', models.CharField(default='pending', max_length=50)),
                ('fee_category', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_premise', models.CharField(blank=True, max_length=100, null=True)),
                ('calculated_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspections.business')),
            ],
        ),
    ]
