# Generated by Django 6.0.4 on 2026-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='building_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='plot_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
