# Generated by Django 6.0.4 on 2026-04-09 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_business_building_name_business_plot_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienterrorlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='clienterrorlog',
            old_name='path',
            new_name='error_name',
        ),
        migrations.RenameField(
            model_name='clienterrorlog',
            old_name='error_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='clienterrorlog',
            old_name='stack_trace',
            new_name='stack',
        ),
        migrations.AddField(
            model_name='clienterrorlog',
            name='client_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienterrorlog',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='clienterrorlog',
            name='environment',
            field=models.CharField(default='production', max_length=50),
        ),
        migrations.AddField(
            model_name='clienterrorlog',
            name='level',
            field=models.CharField(default='error', max_length=50),
        ),
        migrations.AddField(
            model_name='clienterrorlog',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clienterrorlog',
            name='source',
            field=models.CharField(default='client', max_length=100),
        ),
        migrations.AddField(
            model_name='clienterrorlog',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienterrorlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienterrorlog',
            name='user_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clienterrorlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
