# Generated by Django 6.0.4 on 2026-04-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_rename_timestamp_clienterrorlog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='fee_premise',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
