# Generated by Django 6.0.4 on 2026-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_business_contact_person_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='finance_verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
